title: Code‑n‑Hack
description: A blog migrated from WordPress
baseurl: "/code-n-hack"     # your repo name; change if needed
url: "https://GeoTheo06.github.io"
theme: minima               # simple built‑in Jekyll theme